spring:
  application:
    name: job-management-api
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:techarch-kafka1.srv.lab.bthpny.alticeusa.net:9092}
    consumer:
      group-id: ${STREAMMUX_API_CONSUMER_GROUP:job-management-api-read-model-${random.uuid}}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

streammux:
  topics:
    job-definitions: ${STREAMMUX_TOPIC_JOB_DEFINITIONS:job-definitions}
    job-leases: ${STREAMMUX_TOPIC_JOB_LEASES:job-leases}
    job-status: ${STREAMMUX_TOPIC_JOB_STATUS:job-status}
    job-events: ${STREAMMUX_TOPIC_JOB_EVENTS:job-events}
    job-commands: ${STREAMMUX_TOPIC_JOB_COMMANDS:job-commands}
  validation:
    topics:
      allowed-input-topics: ${STREAMMUX_ALLOWED_INPUT_TOPICS:}
      allowed-input-topic-prefixes: ${STREAMMUX_ALLOWED_INPUT_TOPIC_PREFIXES:}
      allowed-output-topics: ${STREAMMUX_ALLOWED_OUTPUT_TOPICS:}
      allowed-output-topic-prefixes: ${STREAMMUX_ALLOWED_OUTPUT_TOPIC_PREFIXES:}
